#!/usr/bin/env bash
#
# Runs ONCE, when the codespace is created. Installs, points the app at the
# throwaway Postgres, migrates, seeds the baseline demo data, and builds.
#
# Everything here is demo-grade on purpose: a generated AUTH_SECRET, the
# built-in sandbox payment gateway, and email written to the server log instead
# of being sent. None of it is production configuration.
set -euo pipefail

PORT=3100

# ---------------------------------------------------------------------------
# The public origin of the forwarded port. Codespaces exposes both halves of it
# as environment variables; NEXT_PUBLIC_SITE_URL is baked in at build time, so
# it has to be correct before `npm run build` runs below — otherwise canonical
# URLs, the sitemap and every emailed link point at localhost.
# ---------------------------------------------------------------------------
if [ -n "${CODESPACE_NAME:-}" ]; then
  SITE_URL="https://${CODESPACE_NAME}-${PORT}.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-app.github.dev}"
else
  SITE_URL="http://localhost:${PORT}"
fi

echo "▶ Installing dependencies"
# Playwright is a devDependency used only by the test suite; its browser
# download is ~400 MB that this demo never opens.
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npm ci

echo "▶ Writing .env  (site URL: ${SITE_URL})"
mkdir -p .dev/media
cat > .env <<ENVEOF
# Generated by .devcontainer/setup.sh for a disposable demo codespace.
# Not production configuration — see .env.example for what a real deploy needs.
DATABASE_URL="postgresql://kiwi:kiwi@localhost:5432/kiwipilotprep?schema=public&connection_limit=10&pool_timeout=10"
AUTH_SECRET="$(openssl rand -base64 32)"
NEXT_PUBLIC_SITE_URL="${SITE_URL}"
MEDIA_DIR="./.dev/media"

# Signs and settles orders locally so checkout can be walked end to end
# without a Razorpay account. Must never be set on a real deploy.
ALLOW_SANDBOX_PAYMENTS="true"

# No Resend key: outgoing mail is logged to the server console rather than
# sent, and EMAIL_DEV_LOG_LINKS puts the verification/reset links in that log
# so a demo signup can actually be completed.
RESEND_API_KEY=""
EMAIL_FROM="KiwiPilotPrep <no-reply@example.com>"
EMAIL_DEV_LOG_LINKS="1"
ENVEOF

echo "▶ Waiting for Postgres"
for _ in $(seq 1 60); do
  if (exec 3<>/dev/tcp/localhost/5432) 2>/dev/null; then
    exec 3<&- 2>/dev/null || true
    break
  fi
  sleep 1
done

echo "▶ Applying migrations"
npm run db:migrate:deploy

echo "▶ Seeding baseline data"
npm run seed

echo "▶ Building"
npm run build

cat <<'DONE'

────────────────────────────────────────────────────────────
  Setup complete. The server starts automatically.

  Sign in with either seeded account:
    admin@kiwipilotprep.com / admin12345
    student@example.com     / student12345
────────────────────────────────────────────────────────────

DONE
