/**
 * The CPL course audit.
 *
 * Three questions, asked separately because a pipeline compared against its own
 * output reports success either way:
 *
 *   1. Does the curriculum account for the whole of each deck? Every slide is
 *      claimed by exactly one topic or listed as skipped with a reason, and
 *      this counts them rather than taking the builder's word for it.
 *
 *   2. Did what the curriculum claims actually reach the database? The stored
 *      blocks are counted by origin and compared against the curriculum.
 *
 *   3. Does the result read like a course? Chapter and topic names are checked
 *      against the failure modes that produced the current CPL course —
 *      sentences promoted to headings, slide numbers, watermark text, generic
 *      single words, near-duplicates — and anything suspicious is listed rather
 *      than silently passed.
 *
 * Writes docs/cms/CPL-INDEX.md (the syllabus, for a human to read) and
 * docs/cms/CPL-AUDIT.md (the three answers above). Exits non-zero if anything
 * needs a person to look at it.
 *
 *   node scripts/cpl-report.mjs [--subject <slug>]
 */
import fs from "node:fs";
import path from "node:path";
import { PrismaClient } from "@prisma/client";

import { loadManifest } from "./deck-index.mjs";
import { SUBJECTS } from "../content/cpl/index.mjs";
import { DROPPED, FLAGGED } from "../content/cpl/diagram-decisions.mjs";

const db = new PrismaClient();
const OUT = "docs/cms";
const COURSE = "cpl-theory";

/** Words that name nothing on their own. A chapter called one of these is a bug. */
const HOLLOW = new Set([
  "operational", "general", "based", "continued", "introduction", "overview",
  "information", "datum", "sector", "standard", "aviation", "precision",
  "magnetic", "control", "error", "static", "drift", "definitions", "summary",
  "notes", "example", "examples", "cpl", "ppl", "types", "effects", "factors",
  "other", "further", "more", "conclusion", "questions", "revision", "contents",
  "index", "recap", "part", "section", "speed", "time", "distance",
]);

/** Titles that are presentation furniture rather than names. */
const FURNITURE_TITLE = [
  /slide\s*no\.?\s*\d/i,
  /\bslide\s*\d/i,
  /\.pptx?\b/i,
  /\.pdf\b/i,
  /^page\s*\d/i,
  /^[➢▪●•]/,
  /commercial pilot academy/i,
  /\bNZICPA\b/i,
];

/** A title that is really a sentence. */
function looksLikeProse(title) {
  const t = title.trim();
  if (/[.!?]$/.test(t)) return true;
  if (t.split(/\s+/).length >= 11) return true;
  if (/\b(the|a|an|of|to|in|on|at|for|with|and|or|is|are)\s*$/i.test(t)) return true;
  return false;
}

/** Comparable form of a title, for spotting near-duplicates. */
const shape = (t) => t.toLowerCase().replace(/[^a-z0-9]+/g, "");

function line(out, text = "") { out.push(text); }

async function main() {
  const only = process.argv.includes("--subject")
    ? process.argv[process.argv.indexOf("--subject") + 1]
    : null;
  const chosen = only ? SUBJECTS.filter((s) => s.slug === only) : SUBJECTS;

  const index = [];
  const audit = [];
  const issues = [];

  line(index, "# KiwiPilotPrep — CPL Theory Syllabus");
  line(index);
  line(index, "Generated by `scripts/cpl-report.mjs`. Do not edit by hand.");
  line(index);

  line(audit, "# CPL Theory — build audit");
  line(audit);

  for (const subject of chosen) {
    const manifest = loadManifest(path.join(".cache/decks", subject.deck));

    /* ---- 1. coverage, counted rather than trusted ---------------------- */
    const owner = new Map();
    const twice = [];
    for (const chapter of subject.chapters) {
      for (const topic of chapter.topics) {
        for (const n of topic.pages) {
          if (owner.has(n)) twice.push(`${n} (${owner.get(n)} / ${topic.title})`);
          owner.set(n, topic.title);
        }
      }
    }
    const skipped = Object.keys(subject.skip ?? {}).map(Number);
    for (const n of skipped) owner.set(n, "(skipped)");
    const unclaimed = [];
    for (let n = 1; n <= manifest.total_slides; n += 1) if (!owner.has(n)) unclaimed.push(n);

    if (twice.length) issues.push(`${subject.slug}: slides claimed twice — ${twice.join(", ")}`);
    if (unclaimed.length) issues.push(`${subject.slug}: slides claimed by nobody — ${unclaimed.join(", ")}`);
    const noReason = Object.entries(subject.skip ?? {})
      .filter(([, r]) => !r || String(r).trim().length < 12)
      .map(([n]) => n);
    if (noReason.length) issues.push(`${subject.slug}: skipped without a reason — ${noReason.join(", ")}`);

    /* ---- 2. what actually reached the database ------------------------- */
    const modules = await db.courseModule.findMany({
      where: { subject: { slug: subject.slug, course: { slug: COURSE } } },
      orderBy: { displayOrder: "asc" },
      select: {
        title: true, summary: true, origin: true, status: true,
        lessons: {
          orderBy: { displayOrder: "asc" },
          select: {
            title: true, slug: true, status: true, sourceFrom: true, sourceTo: true,
            content: { select: { blocks: true } },
          },
        },
      },
    });

    let source = 0, authored = 0, figures = 0, untagged = 0, captioned = 0;
    for (const m of modules) {
      for (const l of m.lessons) {
        for (const b of l.content?.blocks ?? []) {
          if (b.origin === "source") source += 1;
          else if (b.origin === "authored") authored += 1;
          else untagged += 1;
          if (b.type === "figure") { figures += 1; if (b.caption) captioned += 1; }
        }
      }
    }
    if (untagged) issues.push(`${subject.slug}: ${untagged} block(s) carry no origin`);

    const curriculumTopics = subject.chapters.reduce((n, c) => n + c.topics.length, 0);
    const storedTopics = modules.reduce((n, m) => n + m.lessons.length, 0);
    if (modules.length && curriculumTopics !== storedTopics) {
      issues.push(
        `${subject.slug}: curriculum declares ${curriculumTopics} topics but ${storedTopics} are stored — rebuild`,
      );
    }
    const noSummary = modules.filter((m) => !m.summary).map((m) => m.title);
    if (noSummary.length) issues.push(`${subject.slug}: chapter(s) with no summary — ${noSummary.join(", ")}`);
    const notAuthored = modules.filter((m) => m.origin !== "AUTHORED").map((m) => m.title);
    if (notAuthored.length) issues.push(`${subject.slug}: chapter(s) not marked AUTHORED — ${notAuthored.join(", ")}`);

    /* ---- 2b. the CAA syllabus must not be visible teaching -------------- */
    // The reader renders a lesson's confirmed syllabus items as blocks headed
    // "18.2.2 What you need to know", and a subject page describes the CAA
    // syllabus rather than the course whenever that subject has published
    // syllabus rows. IR has none, which is why IR reads as a course. So the
    // check is not "is the wording absent from the blocks" — the rebuild never
    // wrote such wording — it is "can the reader reach a state where it prints
    // the syllabus at a student".
    const subjectRow = await db.subject.findFirst({
      where: { slug: subject.slug, course: { slug: COURSE } },
      select: { id: true },
    });
    const publishedSyllabus = await db.syllabusTopic.count({
      where: { subjectId: subjectRow.id, status: "PUBLISHED", items: { some: { status: "PUBLISHED" } } },
    });
    if (publishedSyllabus > 0) {
      issues.push(
        `${subject.slug}: ${publishedSyllabus} published CAA syllabus topic(s) — the reader will print ` +
          `requirement blocks above the teaching and show the syllabus index instead of the course`,
      );
    }
    const internalMappings = await db.lessonSyllabusItem.count({
      where: { item: { topic: { subjectId: subjectRow.id } } },
    });
    if (internalMappings === 0) {
      issues.push(`${subject.slug}: no internal syllabus mapping — CAA coverage cannot be validated`);
    }

    // Nothing authored may quote CAA wording or a code at the student.
    const caaLeak = [];
    for (const m of modules) {
      for (const l of m.lessons) {
        for (const b of l.content?.blocks ?? []) {
          const text =
            b.type === "keypoints" || b.type === "list"
              ? (b.items ?? []).join(" ")
              : [b.text, b.term, b.title, b.caption].filter(Boolean).join(" ");
          if (/\d{2}\.\d{1,2}\.\d{1,2}/.test(text)) caaLeak.push(`${l.title}: ${text.slice(0, 70)}`);
          if (/what you need to know/i.test(text)) caaLeak.push(`${l.title}: objective wording`);
        }
      }
    }
    if (caaLeak.length) {
      issues.push(`${subject.slug}: CAA syllabus wording inside teaching — ${caaLeak.slice(0, 3).join(" | ")}`);
    }

    /* ---- 3. does it read like a course? -------------------------------- */
    const titles = [
      ...subject.chapters.map((c) => ({ kind: "chapter", title: c.title })),
      ...subject.chapters.flatMap((c) => c.topics.map((t) => ({ kind: "topic", title: t.title }))),
    ];
    for (const { kind, title } of titles) {
      if (HOLLOW.has(title.trim().toLowerCase())) issues.push(`${subject.slug}: hollow ${kind} title "${title}"`);
      if (title.trim().length <= 2) issues.push(`${subject.slug}: ${kind} title too short "${title}"`);
      for (const p of FURNITURE_TITLE) {
        if (p.test(title)) issues.push(`${subject.slug}: furniture in ${kind} title "${title}"`);
      }
      if (looksLikeProse(title)) issues.push(`${subject.slug}: ${kind} title reads as prose "${title}"`);
    }
    const seen = new Map();
    for (const { title } of titles) {
      const k = shape(title);
      seen.set(k, [...(seen.get(k) ?? []), title]);
    }
    for (const [, group] of seen) {
      if (group.length > 1) issues.push(`${subject.slug}: duplicate title "${group[0]}" x${group.length}`);
    }

    /* ---- the syllabus, for a human ------------------------------------- */
    line(index, `## ${subject.title}`);
    line(index);
    line(index, `Source: \`${manifest.source_file}\` — ${manifest.total_slides} slides.`);
    line(index);
    for (const [i, chapter] of subject.chapters.entries()) {
      line(index, `### ${i + 1}. ${chapter.title}`);
      line(index);
      if (chapter.intro) { line(index, chapter.intro); line(index); }
      for (const topic of chapter.topics) {
        const from = Math.min(...topic.pages);
        const to = Math.max(...topic.pages);
        line(index, `- **${topic.title}** — slides ${from === to ? from : `${from}–${to}`}`);
      }
      line(index);
    }

    /* ---- the audit ------------------------------------------------------ */
    line(audit, `## ${subject.title}`);
    line(audit);
    line(audit, "| measure | value |");
    line(audit, "| --- | --- |");
    line(audit, `| source slides | ${manifest.total_slides} |`);
    line(audit, `| claimed by a topic | ${manifest.total_slides - skipped.length} |`);
    line(audit, `| skipped with a written reason | ${skipped.length} |`);
    line(audit, `| claimed twice | ${twice.length} |`);
    line(audit, `| claimed by nobody | ${unclaimed.length} |`);
    line(audit, `| chapters | ${subject.chapters.length} |`);
    line(audit, `| topics | ${curriculumTopics} |`);
    line(audit, `| stored source blocks | ${source} |`);
    line(audit, `| stored authored blocks | ${authored} |`);
    line(audit, `| blocks with no origin | ${untagged} |`);
    line(audit, `| diagrams shown | ${figures} |`);
    line(audit, `| diagrams carrying a note | ${captioned} |`);
    line(audit, `| diagrams rejected on review | ${Object.keys(DROPPED).length} |`);
    line(audit, `| diagrams flagged for a second look | ${Object.keys(FLAGGED).length} |`);
    line(audit, `| CAA syllabus topics visible to a student | ${publishedSyllabus} |`);
    line(audit, `| internal lesson→requirement mappings retained | ${internalMappings} |`);
    line(audit);
    line(audit, "### Slides intentionally skipped");
    line(audit);
    for (const [n, reason] of Object.entries(subject.skip ?? {})) {
      line(audit, `- **${n}** — ${reason}`);
    }
    line(audit);
  }

  line(audit, "## Issues");
  line(audit);
  if (issues.length === 0) line(audit, "None found by this report. That is not the same as none existing — the body scan and the visual review look at different things.");
  for (const i of issues) line(audit, `- ${i}`);

  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, "CPL-INDEX.md"), index.join("\n"));
  fs.writeFileSync(path.join(OUT, "CPL-AUDIT.md"), audit.join("\n"));

  console.log(`wrote ${OUT}/CPL-INDEX.md and ${OUT}/CPL-AUDIT.md`);
  if (issues.length) {
    console.error(`\n${issues.length} issue(s):`);
    for (const i of issues) console.error(`  - ${i}`);
  } else {
    console.log("no issues found");
  }

  await db.$disconnect();
  if (issues.length) process.exit(1);
}

main().catch(async (error) => {
  console.error(error);
  await db.$disconnect();
  process.exit(1);
});
