/**
 * Writes `docs/cms/GROUNDWORK.md` from the supplied documents, the two
 * curricula and the rows in the database.
 *
 * A sibling of `ppl-report.mjs` and written to the same rule: nothing in the
 * page is typed by hand. If the three sources disagree — a module that is not
 * one of the eight the PRD prescribes, a lesson in the curriculum that is not
 * in the database, a count that does not reconcile — the script fails instead
 * of writing a document that says everything is fine.
 *
 *   node scripts/groundwork-report.mjs
 */
import fs from "node:fs";
import { PrismaClient } from "@prisma/client";

import { PRESCRIBED_MODULES } from "./build-groundwork-course.mjs";
import { DROPPED } from "../content/groundwork/ppl-diagrams.mjs";

const db = new PrismaClient();
const MANIFEST = ".cache/groundwork/manifest.json";
const OUT = "docs/cms/GROUNDWORK.md";

const flat = (s) => String(s ?? "").replace(/\s+/g, " ").trim();
const words = (s) => flat(s).split(/\s+/).filter(Boolean).length;

async function read(courseSlug, path) {
  const { curriculum } = await import(path);
  const course = await db.course.findUnique({ where: { slug: courseSlug }, select: { id: true, title: true } });
  if (!course) throw new Error(`no course ${courseSlug}`);
  const subject = await db.subject.findFirst({
    where: { slug: curriculum.subject, courseId: course.id },
    select: { id: true, title: true },
  });
  if (!subject) throw new Error(`no subject ${curriculum.subject} in ${courseSlug}`);

  const modules = await db.courseModule.findMany({
    where: { subjectId: subject.id },
    orderBy: { displayOrder: "asc" },
    select: {
      title: true,
      summary: true,
      lessons: {
        orderBy: { displayOrder: "asc" },
        select: { slug: true, title: true, content: { select: { blocks: true } } },
      },
    },
  });

  const names = modules.map((m) => m.title);
  if (names.length !== PRESCRIBED_MODULES.length || names.some((n, i) => n !== PRESCRIBED_MODULES[i])) {
    throw new Error(`${courseSlug}: the modules are not the eight the PRD prescribes — ${names.join(" | ")}`);
  }

  const inCurriculum = curriculum.modules.flatMap((m) => m.topics.length);
  const stored = modules.map((m) => m.lessons.length);
  if (inCurriculum.join() !== stored.join()) {
    throw new Error(`${courseSlug}: curriculum has ${inCurriculum.join("/")} topics, database has ${stored.join("/")}`);
  }

  let source = 0;
  let authored = 0;
  let figures = 0;
  let wordCount = 0;
  for (const m of modules) {
    for (const l of m.lessons) {
      for (const b of l.content?.blocks ?? []) {
        if (b.origin === "authored") authored += 1;
        else source += 1;
        if (b.type === "figure") figures += 1;
        wordCount += words(b.text) + (b.items ?? []).reduce((n, i) => n + words(i), 0);
      }
    }
  }

  return { course, subject, curriculum, modules, source, authored, figures, wordCount };
}

const ppl = await read("ppl-flight-test", "../content/groundwork/ppl-flight-test.mjs");
const cpl = await read("cpl-flight-test", "../content/groundwork/cpl-flight-test.mjs");

const manifest = JSON.parse(fs.readFileSync(MANIFEST, "utf8"));
const docs = manifest.docs.filter((d) => ppl.curriculum.documents.includes(d.key));
const supplied = docs.reduce((n, d) => n + d.pages.reduce((m, p) => m + p.blocks.length, 0), 0);
const images = docs.reduce((n, d) => n + d.pages.reduce((m, p) => m + p.blocks.filter((b) => b.sha1).length, 0), 0);

// Every supplied image is in one of three places: on a page, rejected by name,
// or on a page that is skipped in its entirety — a cover, a contents page, an
// abbreviation list — where the picture goes with the page. A rejected image
// that also sits on a skipped page is counted once, under the page.
const skippedPages = new Set(Object.keys(ppl.curriculum.skip ?? {}));
let rejected = 0;
let onSkippedPage = 0;
for (const d of docs) {
  for (const page of d.pages) {
    for (const b of page.blocks) {
      if (!b.sha1) continue;
      if (skippedPages.has(`${d.key}:p${page.n}`)) onSkippedPage += 1;
      else if (Object.hasOwn(DROPPED, b.sha1)) rejected += 1;
    }
  }
}
if (rejected + onSkippedPage + ppl.figures !== images) {
  throw new Error(
    `figures do not reconcile: ${ppl.figures} shown + ${rejected} rejected + ` +
      `${onSkippedPage} on skipped pages ≠ ${images} supplied`,
  );
}

const lessons = ppl.modules.reduce((n, m) => n + m.lessons.length, 0);

const lines = [];
const say = (s = "") => lines.push(s);

say("# Flight Test Groundwork — the build");
say();
say("Generated by `scripts/groundwork-report.mjs` from the supplied documents, the curricula in");
say("`content/groundwork/` and the rows in the database. If the three disagree, the script fails");
say("rather than writing this file.");
say();
say("## The eight modules");
say();
say("The PRD (§3.2) prescribes eight modules for Flight Test Groundwork and requires PPL and CPL");
say("to use the same eight. They are modules, not theory subjects, and the list lives in");
say("`PRESCRIBED_MODULES` in `scripts/build-groundwork-course.mjs`; both curricula are checked");
say("against it and a build that renames or reorders one is rejected.");
say();
say("| # | Module | PPL topics | CPL topics |");
say("| ---: | --- | ---: | ---: |");
for (const [i, name] of PRESCRIBED_MODULES.entries()) {
  const p = ppl.modules[i].lessons.length;
  const c = cpl.modules[i].lessons.length;
  say(`| ${i + 1} | ${name} | ${p} | ${c || "—"} |`);
}
say();
say("## PPL");
say();
say("| | |");
say("| --- | ---: |");
say(`| Modules | ${ppl.modules.length} |`);
say(`| Topics | ${lessons} |`);
say(`| Blocks from the supplied material | ${ppl.source} |`);
say(`| Authored blocks | ${ppl.authored} |`);
say(`| Diagrams shown | ${ppl.figures} |`);
say(`| Words a student reads | ${ppl.wordCount.toLocaleString("en-NZ")} |`);
say();
say("### Where the material came from");
say();
say("| Document | Pages | Blocks |");
say("| --- | ---: | ---: |");
for (const d of docs) {
  say(`| ${d.title} | ${d.total_pages} | ${d.pages.reduce((n, p) => n + p.blocks.length, 0)} |`);
}
say(`| **Total** | | **${supplied}** |`);
say();
say("Every one of those blocks is accounted for exactly once. The build refuses to finish");
say("otherwise, and `scripts/groundwork-validate.mjs` adds the same total up again from outside");
say("so a block cannot go missing between the two. A block is either taught, on a page skipped");
say("with a written reason, or removed as the document's own furniture — a page number, a running");
say("head, or a caption for a photograph that is not shown.");
say();
say("### Diagrams");
say();
say(`${images} images came out of the four documents. ${ppl.figures} are shown, ${rejected} were rejected`);
say(`and ${onSkippedPage} sit on pages that are skipped in their entirety. Each rejection has its reason`);
say("recorded against the image's SHA-1 in");
say("`content/groundwork/ppl-diagrams.mjs`, so the decision survives re-extraction. The rejected");
say("ones are the word processor's own bullet icons and template placeholder, the airspace");
say("booklet's stock photography, and one table supplied twice.");
say();
say("### The Examiner Hot Seat");
say();
say("The supplied questions document contains oral questions written as prompt, common trap and");
say("model answer. They are study material, not a question bank: there are no options and no key,");
say("and the app's `Question` rows are single-choice, so turning them into questions would mean");
say("inventing wrong answers. They are therefore the last topic of each module, in the form they");
say("were written, and nothing was added to them.");
say();
say("## CPL");
say();
say("No CPL Flight Test Groundwork material has been supplied. The eight modules exist, each with");
say("a summary describing what it will cover and a note saying the material is in preparation, and");
say("there are no topics. Nothing was copied from PPL — a commercial candidate reading PPL");
say("privileges and PPL fuel reserves would be studying the wrong requirements — and nothing was");
say("written to fill the gap, because teaching that looks like client material but is not is worse");
say("than an empty module that says so.");
say();
say("When the material arrives, `content/groundwork/cpl-flight-test.mjs` says what to do with it.");
say();
say("## One table the source cannot establish");
say();
say("The airspace classification table in the study document is flattened past the point where");
say("its cells can be put back. Class D prints three flight rules and seven statements where six");
say("are needed; Class C prints six that do not divide the way its column order implies. Any grid");
say("built from them would be a guess about which service belongs to which flight rule, which is");
say("the one thing not worth guessing on a page about separation.");
say();
say("So the class labels are separated from the words the PDF welded to them, the statements are");
say("left exactly as the client wrote them, and no grid is invented. The whole of the");
say("classification material — Class G, Class D and Class C — is read in one topic rather than");
say("split across two, which is where the document happened to print it.");
say();
say("This is a source-quality issue rather than a build one. Closing it properly needs the");
say("original table from the client.");
say();
say("## Checked against the flight test itself");
say();
say("The authority is the CAA's own form — **Part 61 private pilot licence, aeroplane flight");
say("test report, CAA 24061-22** — and `scripts/groundwork-caa-check.mjs` reconciles the eight");
say("modules against it. The first eight tasks the examiner marks on that form are the eight");
say("modules the PRD prescribes, with the same names in the same order, and every objective the");
say("form prints beside them is checked against what the module actually teaches.");
say();
say("The twenty-three tasks after those eight are flown rather than briefed and are outside this");
say("product. They are listed by the check rather than folded into a module where they would not");
say("belong. The six written examinations the form records dates for are PPL Theory, a separate");
say("course.");
say();
say("The check is internal. Nothing it produces reaches a student, and the form's wording never");
say("appears on a page.");
say();
say("Three of the objectives the form names were not reached by the supplied material: securing");
say("the load, the interior check, and load security. They are closed with authored context on");
say("the topics a student is already reading when the question arises, in the same bounded way");
say("the theory courses add explanation. The regulatory statements in that context come from the");
say("current Part 91 consolidation — 91.213 carry-on baggage, 91.215 carriage of cargo, 91.219");
say("familiarity with limitations and emergency equipment — and everything else defers to the");
say("flight manual for the type rather than asserting a procedure of its own. No aircraft-specific");
say("procedure, limitation or number is invented, and none of it is attributed to the client.");
say();
say("## What was left alone");
say();
say("The courses, the subjects, the products that grant them and the entitlements that reference");
say("them all existed already; this build looks them up and never creates them. The chapter rows");
say("were kept with their ids and their progress, and only their content was rewritten — they had");
say("been seeded with placeholder text telling students the real material is uploaded through the");
say("admin console.");
say();
const archived = await db.subject.count({
  where: { course: { slug: { in: ["ppl-flight-test", "cpl-flight-test"] } }, status: "ARCHIVED" },
});
say(`${archived} archived subjects remain on the two courses, left from an earlier attempt that`);
say("modelled the eight modules as subjects. They are empty, archived and unreachable, and are");
say("kept rather than deleted so nothing that once referenced them breaks.");
say();

fs.mkdirSync("docs/cms", { recursive: true });
fs.writeFileSync(OUT, `${lines.join("\n")}\n`);
console.log(`${OUT} — ${lines.length} lines`);
await db.$disconnect();
