/**
 * The IR course audit.
 *
 * Three questions, asked separately because a pipeline compared against its own
 * output reports success either way:
 *
 *   1. Does the curriculum account for the whole of each manual? Every page is
 *      claimed by exactly one topic or listed as skipped with a reason, and
 *      this counts them rather than taking the builder's word for it.
 *
 *   2. Did what the curriculum claims actually reach the database? The stored
 *      blocks are counted by origin and compared against the manifests.
 *
 *   3. Does the result read like a course? Chapter and topic names are checked
 *      against the failure modes that produced the last version of this course
 *      — sentences promoted to headings, generic single words, near-duplicates
 *      — and anything suspicious is listed rather than silently passed.
 *
 * Writes docs/cms/IR-INDEX.md (the syllabus, for a human to read) and
 * docs/cms/IR-AUDIT.md (the three answers above).
 *
 *   node scripts/ir-report.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { PrismaClient } from "@prisma/client";

import { loadManifest } from "./deck-index.mjs";
import { SUBJECTS } from "../content/ir/index.mjs";
import { DROPPED, FLAGGED } from "../content/ir/diagram-decisions.mjs";

const db = new PrismaClient();
const OUT = "docs/cms";
const COURSE = "ir-theory";

/** Words that name nothing on their own. A chapter called one of these is a bug. */
const HOLLOW = new Set([
  "operational", "general", "based", "continued", "introduction", "overview",
  "information", "datum", "sector", "standard", "aviation", "precision",
  "magnetic", "control", "error", "static", "drift", "definitions",
]);

/** A title that is a sentence is body text that was mistaken for a heading. */
function looksLikeProse(title) {
  const words = title.trim().split(/\s+/);
  if (words.length > 9) return true;
  if (/[.!?]$/.test(title.trim())) return true;
  // A finite verb early in a short phrase is the signature of a sentence
  // ("The climb just about finished", "We can remember the errors easily").
  return /^(we|you|it|this|there|now|so|lets|let's)\b/i.test(title.trim());
}

/** Two titles that differ only in case or punctuation are one title twice. */
const normalise = (title) => title.toLowerCase().replace(/[^a-z0-9]+/g, "");

function countByOrigin(blocks) {
  const out = { source: 0, authored: 0, figures: 0, captioned: 0 };
  for (const block of blocks ?? []) {
    if (block.type === "figure") {
      out.figures += 1;
      if (block.caption) out.captioned += 1;
      if (block.origin === "authored") out.authored += 1;
      else out.source += 1;
      continue;
    }
    if (block.origin === "authored") out.authored += 1;
    else out.source += 1;
  }
  return out;
}

async function main() {
  const index = [
    "# IR — the syllabus",
    "",
    "Chapters and topics as a student meets them. This is generated from the",
    "course in the database, not from the curriculum files, so it shows what is",
    "actually published.",
    "",
  ];

  const audit = [
    "# IR — course audit",
    "",
    "Generated by `scripts/ir-report.mjs`. Three independent checks: that the",
    "curriculum accounts for every page of every manual, that what it claims",
    "reached the database, and that the resulting names read like a syllabus.",
    "",
  ];

  const summary = [];
  const problems = [];

  for (const subject of SUBJECTS) {
    const manifest = loadManifest(path.join(".cache/decks", subject.deck));

    /* ---- 1. coverage, counted here rather than trusted ------------------ */

    const claimed = new Map();
    for (const chapter of subject.chapters) {
      for (const topic of chapter.topics) {
        for (const n of topic.pages) claimed.set(n, topic.title);
      }
    }
    const skipped = Object.keys(subject.skip ?? {}).map(Number);
    const unclaimed = [];
    for (let n = 1; n <= manifest.total_slides; n += 1) {
      if (!claimed.has(n) && !skipped.includes(n)) unclaimed.push(n);
    }
    if (unclaimed.length) {
      problems.push(`${subject.slug}: ${unclaimed.length} source page(s) in no topic`);
    }

    /* ---- 2. what actually reached the database -------------------------- */

    const modules = await db.courseModule.findMany({
      where: { status: "PUBLISHED", subject: { slug: subject.slug, course: { slug: COURSE } } },
      orderBy: { displayOrder: "asc" },
      select: {
        title: true, summary: true, origin: true,
        lessons: {
          where: { status: "PUBLISHED" },
          orderBy: { displayOrder: "asc" },
          select: { title: true, slug: true, content: { select: { blocks: true } } },
        },
      },
    });

    const stored = { source: 0, authored: 0, figures: 0, captioned: 0 };
    for (const module of modules) {
      for (const lesson of module.lessons) {
        const counts = countByOrigin(lesson.content?.blocks);
        stored.source += counts.source;
        stored.authored += counts.authored;
        stored.figures += counts.figures;
        stored.captioned += counts.captioned;
      }
    }

    const topics = modules.flatMap((m) => m.lessons);
    const emptyTopics = topics.filter((l) => (l.content?.blocks ?? []).length === 0);
    const emptyChapters = modules.filter((m) => m.lessons.length === 0);
    if (emptyTopics.length) problems.push(`${subject.slug}: ${emptyTopics.length} empty topic(s)`);
    if (emptyChapters.length) problems.push(`${subject.slug}: ${emptyChapters.length} empty chapter(s)`);

    // Every topic should carry some authored teaching, or it is a page of the
    // manual with a new name rather than a topic of a course.
    const bare = topics.filter((l) => countByOrigin(l.content?.blocks).authored === 0);

    /* ---- 3. do the names read like a syllabus? --------------------------- */

    const names = [...modules.map((m) => m.title), ...topics.map((l) => l.title)];
    const prose = names.filter(looksLikeProse);
    const hollow = names.filter((n) => HOLLOW.has(n.trim().toLowerCase()));
    const seen = new Map();
    const nearDupes = [];
    for (const name of names) {
      const key = normalise(name);
      if (seen.has(key) && seen.get(key) !== name) nearDupes.push(`${seen.get(key)} / ${name}`);
      else if (seen.has(key)) nearDupes.push(`${name} (twice)`);
      seen.set(key, name);
    }
    if (prose.length) problems.push(`${subject.slug}: ${prose.length} title(s) read as prose`);
    if (hollow.length) problems.push(`${subject.slug}: ${hollow.length} title(s) are a hollow word`);
    if (nearDupes.length) problems.push(`${subject.slug}: ${nearDupes.length} near-duplicate title(s)`);

    /* ---- the index ------------------------------------------------------- */

    index.push(`## ${subject.title}`, "");
    index.push(
      `${modules.length} chapters · ${topics.length} topics · ` +
        `${manifest.total_slides} source pages`,
      "",
    );
    modules.forEach((module, i) => {
      index.push(`### ${i + 1}. ${module.title}`);
      if (module.summary) index.push("", module.summary);
      index.push("");
      module.lessons.forEach((lesson, j) => index.push(`${i + 1}.${j + 1} ${lesson.title}`));
      index.push("");
    });

    /* ---- the audit section ---------------------------------------------- */

    audit.push(
      `## ${subject.title}`,
      "",
      `- **Source pages:** ${manifest.total_slides}`,
      `- **Pages claimed by a topic:** ${claimed.size}`,
      `- **Pages deliberately skipped:** ${skipped.length}${
        skipped.length ? ` (${skipped.map((n) => `p${n}: ${subject.skip[n]}`).join("; ")})` : ""
      }`,
      `- **Pages in no topic:** ${unclaimed.length ? unclaimed.join(", ") : "none"}`,
      `- **Chapters:** ${modules.length}, all ${
        new Set(modules.map((m) => m.origin)).size === 1 ? modules[0]?.origin ?? "—" : "mixed origin"
      }`,
      `- **Topics:** ${topics.length}`,
      `- **Empty topics:** ${emptyTopics.length}`,
      `- **Empty chapters:** ${emptyChapters.length}`,
      `- **Source blocks stored:** ${stored.source}`,
      `- **Authored blocks stored:** ${stored.authored}`,
      `- **Topics with no authored teaching:** ${bare.length}${
        bare.length ? ` — ${bare.slice(0, 6).map((l) => l.title).join("; ")}` : ""
      }`,
      `- **Diagrams:** ${stored.figures}, of which ${stored.captioned} carry a "what this shows" note`,
      `- **Titles reading as prose:** ${prose.length ? prose.join("; ") : "none"}`,
      `- **Titles that are a hollow word:** ${hollow.length ? hollow.join("; ") : "none"}`,
      `- **Near-duplicate titles:** ${nearDupes.length ? nearDupes.join("; ") : "none"}`,
      "",
    );

    summary.push({
      subject: subject.title,
      pages: manifest.total_slides,
      chapters: modules.length,
      topics: topics.length,
      source: stored.source,
      authored: stored.authored,
      diagrams: stored.figures,
      unclaimed: unclaimed.length,
      proseTitles: prose.length,
      dupeTitles: nearDupes.length,
    });
  }

  /* ---- diagrams, across the course --------------------------------------- */

  audit.push(
    "## Diagrams",
    "",
    "The measurable rules in the extractor remove what is invisible — a backdrop",
    "at low opacity, a logo repeated on forty pages. They cannot remove a sharp,",
    "deliberate photograph of a road at sunset. Every image in the course was",
    "looked at, and these are the results of that review.",
    "",
    `- **Removed on review:** ${Object.keys(DROPPED).length} images`,
    `- **Kept but flagged as a close call:** ${Object.keys(FLAGGED).length} images`,
    "",
    "### Removed",
    "",
    ...Object.values(DROPPED)
      .reduce((acc, why) => {
        const at = acc.findIndex((row) => row.why === why);
        if (at > -1) acc[at].n += 1;
        else acc.push({ why, n: 1 });
        return acc;
      }, [])
      .map((row) => `- ${row.n} × ${row.why}`),
    "",
    "### Flagged for a second opinion",
    "",
    ...Object.values(FLAGGED).map((why) => `- ${why}`),
    "",
  );

  audit.push(
    "## Result",
    "",
    problems.length
      ? `**${problems.length} issue(s):**\n\n${problems.map((p) => `- ${p}`).join("\n")}`
      : "**No issues.** Every page of every manual is accounted for, every topic " +
        "carries content, and no chapter or topic name reads as extracted text.",
    "",
  );

  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, "IR-INDEX.md"), index.join("\n"), "utf8");
  fs.writeFileSync(path.join(OUT, "IR-AUDIT.md"), audit.join("\n"), "utf8");

  console.table(summary);
  if (problems.length) {
    console.log(`\n${problems.length} issue(s):`);
    for (const p of problems) console.log(`  - ${p}`);
  } else {
    console.log("\nno issues");
  }
  console.log(`\nwrote ${OUT}/IR-INDEX.md and ${OUT}/IR-AUDIT.md`);

  await db.$disconnect();
  process.exit(problems.length ? 1 : 0);
}

main().catch(async (error) => {
  console.error(error);
  await db.$disconnect();
  process.exit(1);
});
